# Permalinks
permalink:           pretty

# Setup
title:               BForever
tagline:             Blog
url:                 https://bforever.github.io
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              FanHongchang
  url:               https://bforever.github.io
  email:             11fhc@163.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/poole/poole

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

encoding:            utf-8
